#!/usr/bin/env node
// new-reader.mjs — dependency-free reader scaffolder for class (b) deploys.
//
//   node tools/live-circuit/new-reader.mjs <name> [--route /api/circuit/v1/<name>]
//     [--source <sourceId>] [--reader <readerId>] [--procedure analysis.read_<name>]
//     [--operation invoke|list] [--capability read-<name>]
//     [--input-contract <name>-request.v1] [--output-contract <name>.v1]
//     [--fields a,b] [--out <dir>] [--list] [--force]
//
// Emits the K5 reader scaffold checklist as stub files under <dir> (default
// tools/live-circuit/generated/readers/<name>), itemising one-time vs per-reader
// deploy costs:
//   CHECKLIST.md                        ordered surfaces + cost itemisation
//   estate/<name>.reading.preflight.sql   declare-ui-page-reading pair (ROLLBACK)
//   estate/<name>.reading.commit.sql      the COMMIT twin + proof skeleton
//   platform/circuit-host.readers.patch.json   readers entry
//   platform/live-store.reader.patch.mjs       read fn + source set + dispatch
//   platform/ui-registry.source.patch.json     sources entry (K2 regeneration)
//   platform/accept.pins.patch.txt             accept.mjs / verify-pages pins
//
// Readers are GET-only with no method, header or credential; the scaffolder
// refuses those specs (analysis/07 §K5, implementation-strategy.md §4.4:295).
// The in-transaction proof stays hand-owned: the generated SQL is a reviewable
// skeleton, never evidence. --list is a dry run and writes nothing.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..');
const hostPolicyPath = path.join(repoRoot, 'live-circuit', 'circuit', 'circuit-host.json');
const liveStorePath = path.join(repoRoot, 'live-circuit', 'circuit', 'live-store.mjs');
const acceptPath = path.join(repoRoot, 'deploy', 'staging', 'accept.mjs');
const namePattern = /^[a-z][a-z0-9-]*$/;
const fieldPattern = /^[A-Za-z][A-Za-z0-9._-]*$/;

function usage() {
  return [
    'usage: node tools/live-circuit/new-reader.mjs <name> [--route <path>] [--source <id>] [--reader <id>]',
    '       [--procedure <schema.procedure>] [--operation invoke|list] [--capability <id>]',
    '       [--input-contract <id>] [--output-contract <id>] [--fields a,b] [--out <dir>] [--list] [--force]',
  ].join('\n');
}
function parseArgs(argv, allowed) {
  const values = new Map(), positional = [];
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    if (!arg.startsWith('--')) { positional.push(arg); continue; }
    const name = arg.slice(2);
    if (name === 'help' || name === 'h') { values.set('help', true); continue; }
    if (!allowed.has(name)) throw new Error(`unknown option --${name}`);
    const next = argv[index + 1];
    if (next === undefined || next.startsWith('--')) values.set(name, true);
    else { values.set(name, next); index++; }
  }
  return { positional, value: name => values.get(name), has: name => values.has(name) };
}
function camelCase(name) {
  return name.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}
function sqlName(name) {
  return name.replace(/-/g, '_');
}
function requireName(value, label) {
  if (typeof value !== 'string' || !namePattern.test(value)) throw new Error(`${label} "${value}" must match ${namePattern}`);
  return value;
}

const costTable = [
  '| Cost | One-time (paid in Phase 0 / K1-K4) | Per reader |',
  '| --- | --- | --- |',
  '| Estate | pair conventions, the `sidefx_ui` schema, the capability/port/proof pattern and seeds | one migration pair generated from the spec plus a hand-owned in-transaction proof; no `sfx-dal` registration and no retrieval policy (`implementation-strategy.md` §7.3-7.4) |',
  '| Platform | route host, registry manifest, publish gate, conformance harness, fixtures | reader entry, read function/route, registry regeneration, acceptance pin: ~30-80 generated lines |',
  '| Client | `page-runtime.js`, `ui-components.js`, `page.js` | none unless a payload transform module is added; then a `CIRCUIT_FILES` entry + pin (class (a)) |',
  '| Gate | full staging acceptance machinery | one `verify-pages`/`verify-reader` run and one publish drill |',
];

function checklist(spec, files) {
  return `# Reader scaffold: ${spec.reader}

Generated by \`tools/live-circuit/new-reader.mjs\`; scaffold only — the estate proof and
every acceptance receipt stay hand-owned. Pattern: the declared reader pair
\`sfx-embody/sql/migrations/declare-ui-page-reading.commit.sql\` (schema/content tables
:73-115, single-value reader :227-299, capability + root scenario :402-473, port binding
:474-528, in-transaction proof :530-682).

Spec: reader=\`${spec.reader}\` source=\`${spec.sourceId}\` route=\`${spec.route}\`
operation=\`${spec.operation}\` capability=\`${spec.capabilityId}\` procedure=\`${spec.procedure}\`
contracts=\`${spec.inputContractId}\`/\`${spec.outputContractId}\` fields=[${spec.fields.join(', ')}].

## Ordered checklist

- [ ] **Estate pair** — install \`${files.estatePreflight}\` as the preflight and
      \`${files.estateCommit}\` as the commit twin through the SDA-checkout lifecycle.
      No \`sfx-dal\` registration, no retrieval-policy entry, no gateway change: the
      gateway already proxies \`/api/circuit/*\` and 405s everything but the admitted POSTs.
- [ ] **\`circuit-host.json\` readers entry** — merge \`${files.hostReadersPatch}\`
      into \`readers\` (\`circuit-host.json:18-23\`).
- [ ] **\`live-store.mjs\` source route** — merge \`${files.storePatch}\`: add
      \`'${spec.sourceId}'\` to the source set (\`live-store.mjs:241\`), the \`read${camelCase(spec.reader)}\`
      function beside \`readPage\` (\`live-store.mjs:267-302\`) and the dispatch branch
      (\`live-store.mjs:388-394\`), with the payload whitelist, GET-only rule and refusal map.
- [ ] **\`ui-registry\` sources entry** — merge \`${files.registryPatch}\` into the
      generated registry (K2), then regenerate the served and client copies.
- [ ] **\`accept.mjs\` pins** — merge \`${files.acceptPins}\`; if the source feeds a
      declared page, extend \`verify-pages.mjs:20\` expected sources and add a group for
      the new route body contract.
- [ ] **Fixture + reader verification** — add a page fixture (K4) and a
      \`verify-reader.mjs\` stub asserting \`contractId\` equality, refusal statuses and
      GET/405 route policy.
- [ ] **Publish drill** — one \`publish-ui-page\` run (stage → candidate verify →
      promote → post-verify) and the WP1.x receipt per \`implementation-strategy.md\` §9.2.

## One-time vs per-reader deploy costs

${costTable.join('\n')}

## Rule

A reader is GET-only and names no method, header or credential; this scaffolder
refuses those specs. Generated SQL and patches are reviewable skeletons: the
in-transaction proof is where the meaning lives and stays hand-owned.
`;
}

function estatePreflight(spec) {
  const table = `${sqlName(spec.sourceId)}_reading`;
  return `-- Generated scaffold: ${spec.reader} reader migration pair (PREFLIGHT, ends in ROLLBACK).
-- Pattern: sfx-embody/sql/migrations/declare-ui-page-reading.commit.sql (:73-115, :227-299,
-- :402-473, :474-528). This skeleton is not evidence and is not complete; review before install.

BEGIN;

-- 1. Content tables (declare-ui-page-reading.commit.sql:73-115).
CREATE SCHEMA IF NOT EXISTS sidefx_ui;
CREATE TABLE IF NOT EXISTS sidefx_ui.${table} (
  reading_id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reading_key               text NOT NULL,
  document                  jsonb NOT NULL,
  document_digest           text NOT NULL CHECK (document_digest ~ '^[a-f0-9]{64}$'),
  reading_definition_sha256 text NOT NULL,
  read_at                   timestamptz NOT NULL DEFAULT now()
);

-- 2. Single-value reader analysis.read_${sqlName(spec.reader)} (:227-299).
--    Refuses invalid input with named THROWs; never returns an empty document.
CREATE OR REPLACE FUNCTION analysis.read_${sqlName(spec.reader)}(p_key text)
RETURNS TABLE (contract_id text, document jsonb, reading_definition_sha256 text)
LANGUAGE plpgsql AS $$
BEGIN
  IF p_key IS NULL OR p_key = '' THEN
    RAISE EXCEPTION '${spec.inputContractId.toUpperCase().replace(/[^A-Z0-9]+/g, '_')}_INVALID';
  END IF;
  -- TODO: read the content rows for p_key; one row out.
  RAISE EXCEPTION 'NOT_IMPLEMENTED_${sqlName(spec.sourceId).toUpperCase()}';
END;
$$;

-- 3. Capability ${spec.capabilityId} with ${spec.inputContractId} / ${spec.outputContractId}
--    and one root terminal scenario (:402-473).

-- 4. Port binding to sda-embodiment-plan-port.v1 / sda-declared-read-graph-provider.v1
--    plus the grant (:474-528).

ROLLBACK;
`;
}

function estateCommit(spec) {
  const preflight = estatePreflight(spec).replace('(PREFLIGHT, ends in ROLLBACK)', '(COMMIT twin)')
    .replace(/ROLLBACK;\s*$/, `COMMIT;

-- 5. In-transaction proof skeleton (:530-682) — HAND-OWNED.
--    Prove, inside this transaction, that the reader returns the declared
--    ${spec.outputContractId} document and that every refusal throws:
--      * install the content row and call analysis.read_${sqlName(spec.reader)};
--      * assert contract_id = '${spec.outputContractId}';
--      * assert an invalid key raises the named refusal above;
--      * assert the reading_definition_sha256 matches the declared reader body.
-- TODO(author): replace this skeleton with the real proof before install.
`);
  return preflight;
}

function hostReadersPatch(spec) {
  const request = spec.operation === 'list'
    ? { object: 'capability', verb: 'list' }
    : { object: 'capability', verb: 'invoke', subject: spec.capabilityId };
  return JSON.stringify({
    readers: {
      [spec.reader]: {
        operation: spec.operation,
        request,
        inputContractId: spec.inputContractId,
        outputContractId: spec.outputContractId,
      },
    },
  }, null, 2) + '\n';
}

function storePatch(spec) {
  const fn = `read${camelCase(spec.reader)}`;
  const fields = spec.fields.length ? `'${spec.fields.join("', '")}'` : '';
  const required = spec.fields[0] ?? null;
  return `// Generated reader patch for "${spec.reader}" — merge into
// live-circuit/circuit/live-store.mjs beside readPage (:267-302).
//   1. add '${spec.sourceId}' to the pageSources set (:241)
//   2. add ${fn} below
//   3. add the dispatch branch (:388-394):
//      else if (url.pathname === '${spec.route}') data = await ${fn}(Object.fromEntries([${fields}].map(k => [k, url.searchParams.get(k)])), refresh);

export const PAGE_SOURCE_ID = '${spec.sourceId}';

export async function ${fn}(selection, refresh = false) {
  const payload = {};
  for (const key of [${fields}]) {
    const value = selection[key];
    if (value == null || value === '') continue;
    if (typeof value !== 'string' || value.length > 400 || /[\\u0000-\\u001f]/.test(value))
      throw new CircuitReadError('INVALID_CIRCUIT_SELECTION', 400);
    payload[key] = value;
  }
  ${required ? `if (!payload.${required}) throw new CircuitReadError('${spec.sourceId.toUpperCase().replace(/-/g, '_')}_REQUIRED', 400);` : '// TODO: require the request contract fields.'}
  const { data } = await read('${spec.reader}', payload, refresh);
  if (data.contractId !== '${spec.outputContractId}') throw new CircuitReadError('CIRCUIT_SELECTION_MISMATCH');
  return { ...data, source: 'database' };
}
`;
}

function registryPatch(spec) {
  return JSON.stringify({
    sources: [{ sourceId: spec.sourceId, reader: spec.reader, route: spec.route }],
  }, null, 2) + '\n';
}

function acceptPins(spec) {
  return `# Generated acceptance pins for reader "${spec.reader}".
# Merge into deploy/staging/accept.mjs public mode (route list :47-48):
['${spec.route}', 'GET', 200],
# The registry group (verify-pages.mjs:127-136) asserts every sourceId; add
# '${spec.sourceId}' to expectedSources when this source feeds a declared page.
# Reader checks stay hand-owned: contractId equality, refusal statuses and the
# GET/405 route policy (deploy/sda-kernel/gateway.mjs:157-164).
`;
}

async function inspectCollisions(spec) {
  const policy = JSON.parse(await readFile(hostPolicyPath, 'utf8'));
  const collisions = [];
  if (policy?.readers?.[spec.reader]) collisions.push(`circuit-host.json already declares the reader "${spec.reader}"`);
  const store = await readFile(liveStorePath, 'utf8');
  const sources = store.match(/const pageSources = new Set\(\[([^\]]*)\]\)/)?.[1] ?? '';
  for (const sourceId of sources.split(',').map(item => item.trim().replace(/['"]/g, '')).filter(Boolean))
    if (sourceId === spec.sourceId) collisions.push(`live-store.mjs pageSources already declares "${spec.sourceId}"`);
  if (store.includes(`'${spec.route}'`)) collisions.push(`live-store.mjs already routes ${spec.route}`);
  const accept = await readFile(acceptPath, 'utf8');
  if (accept.includes(`'${spec.route}'`)) collisions.push(`accept.mjs already pins ${spec.route}`);
  return collisions;
}

async function scaffold(name, options) {
  requireName(name, 'reader name');
  const spec = {
    reader: options.reader === undefined ? name : requireName(options.reader, 'reader id'),
    sourceId: options.source === undefined ? name : requireName(options.source, 'source id'),
    route: options.route === undefined ? `/api/circuit/v1/${name}` : options.route,
    procedure: options.procedure === undefined ? `analysis.read_${sqlName(name)}` : options.procedure,
    operation: options.operation === undefined ? 'invoke' : options.operation,
    capabilityId: options.capability === undefined ? `read-${name}` : options.capability,
    inputContractId: options['input-contract'] === undefined ? `${name}-request.v1` : options['input-contract'],
    outputContractId: options['output-contract'] === undefined ? `${name}.v1` : options['output-contract'],
    fields: [],
  };
  if (!/^\/api\/circuit\/v1\/[a-z0-9-]+$/.test(spec.route)) throw new Error(`--route "${spec.route}" must match /api/circuit/v1/<name>`);
  if (spec.operation !== 'invoke' && spec.operation !== 'list') throw new Error('--operation must be invoke or list');
  if (typeof spec.procedure !== 'string' || !/^[a-z_][a-z0-9_]*\.[a-z_][a-z0-9_]*$/.test(spec.procedure))
    throw new Error(`--procedure "${spec.procedure}" must be schema.procedure`);
  if (options.fields !== undefined && options.fields !== true) {
    spec.fields = String(options.fields).split(',').map(item => item.trim()).filter(Boolean);
    for (const field of spec.fields) if (!fieldPattern.test(field)) throw new Error(`--fields entry "${field}" is not a valid field name`);
  }
  const collisions = await inspectCollisions(spec);
  if (collisions.length) throw new Error(collisions.join('; '));

  const files = {
    checklist: 'CHECKLIST.md',
    estatePreflight: `estate/${name}.reading.preflight.sql`,
    estateCommit: `estate/${name}.reading.commit.sql`,
    hostReadersPatch: 'platform/circuit-host.readers.patch.json',
    storePatch: 'platform/live-store.reader.patch.mjs',
    registryPatch: 'platform/ui-registry.source.patch.json',
    acceptPins: 'platform/accept.pins.patch.txt',
  };
  const outputs = [
    [files.checklist, checklist(spec, files)],
    [files.estatePreflight, estatePreflight(spec)],
    [files.estateCommit, estateCommit(spec)],
    [files.hostReadersPatch, hostReadersPatch(spec)],
    [files.storePatch, storePatch(spec)],
    [files.registryPatch, registryPatch(spec)],
    [files.acceptPins, acceptPins(spec)],
  ];
  return { spec, files, outputs };
}

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) { console.log(usage()); process.exit(0); }
try {
  const refused = ['method', 'header', 'credential'].filter(flag => args.some(arg => arg.startsWith(`--${flag}`)));
  if (refused.length) throw new Error(`readers are GET-only: refusing ${refused.map(flag => `--${flag}`).join(', ')}`);
  const parsed = parseArgs(args, new Set(['route', 'source', 'reader', 'procedure', 'operation', 'capability',
    'input-contract', 'output-contract', 'fields', 'out', 'list', 'force', 'help']));
  if (parsed.has('help')) { console.log(usage()); process.exit(0); }
  if (parsed.positional.length !== 1) { console.error(usage()); process.exit(2); }
  const name = parsed.positional[0];
  const result = await scaffold(name, {
    route: parsed.value('route') === true ? undefined : parsed.value('route'),
    source: parsed.value('source') === true ? undefined : parsed.value('source'),
    reader: parsed.value('reader') === true ? undefined : parsed.value('reader'),
    procedure: parsed.value('procedure') === true ? undefined : parsed.value('procedure'),
    operation: parsed.value('operation') === true ? undefined : parsed.value('operation'),
    capability: parsed.value('capability') === true ? undefined : parsed.value('capability'),
    'input-contract': parsed.value('input-contract') === true ? undefined : parsed.value('input-contract'),
    'output-contract': parsed.value('output-contract') === true ? undefined : parsed.value('output-contract'),
    fields: parsed.value('fields'),
  });
  const outDir = path.resolve(process.cwd(), parsed.value('out') === true || parsed.value('out') === undefined
    ? path.join(here, 'generated', 'readers', name) : parsed.value('out'));
  if (parsed.has('list')) {
    console.log(JSON.stringify({ tool: 'new-reader.mjs', mode: 'list', outDir, files: result.outputs.map(([file]) => file) }, null, 2));
  } else {
    if (!parsed.has('force')) {
      const existing = [];
      for (const [file] of result.outputs) {
        try { await readFile(path.join(outDir, file)); existing.push(file); } catch { /* absent is fine */ }
      }
      if (existing.length) throw new Error(`${existing.join(', ')} already exist under ${outDir}; pass --force to overwrite`);
    }
    await mkdir(outDir, { recursive: true });
    for (const [file, text] of result.outputs) {
      await mkdir(path.dirname(path.join(outDir, file)), { recursive: true });
      await writeFile(path.join(outDir, file), text, 'utf8');
    }
    console.log(JSON.stringify({
      tool: 'new-reader.mjs',
      mode: 'scaffold',
      reader: result.spec.reader,
      sourceId: result.spec.sourceId,
      route: result.spec.route,
      outDir,
      files: result.outputs.map(([file]) => file),
      costs: { oneTime: ['estate pair conventions / schema / capability-port-proof pattern / seeds', 'route host, registry manifest, publish gate, conformance harness, fixtures', 'client runtime modules', 'full staging acceptance machinery'], perReader: ['one migration pair + hand-owned proof', 'reader entry, read function/route, registry regeneration, acceptance pin (~30-80 lines)', 'none unless a transform module is added', 'one verify run + one publish drill'] },
    }, null, 2));
  }
} catch (error) {
  console.error(`new-reader.mjs: ${error.message}`);
  process.exitCode = 1;
}
